<?php
use Drupal\Component\Utility\Html;
use http\Client\Curl\User;

/**
 * Implements hook_preprocess_page().
 *
 */
function bcmp_user_preprocess_page(&$variables) {
//	print_r(\Drupal::routeMatch()->getRouteName());
}


/**
 * Implements hook_theme().
 */
function bcmp_user_theme()
{
  return[
    'bcmp_set_password' =>[
      'render element' => 'children',
      'variables'
    ]];
}
/**
 * Implements hook_mail().
 */
function bcmp_user_mail($key, &$message, $params) {
  switch ($key) {
    case 'verify_email':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('ელ.ფოსტის ვერიფიკაცია bitcamp.ge-ზე');
      $message['body'][] = Html::escape($params['message']);
      break;
  }
}
